test_size: 0.3
threshold: 120

eol:
  param_grid:
    regressor__n_estimators:
      - 100
      - 200
      - 300
    regressor__learning_rate:
      - 0.01
      - 0.1
    regressor__max_depth:
      - 3
      - 4
      - 5
      - 6
  signature_depth: 3
  scorer: neg_mean_absolute_error

rul:
  param_grid:
    regressor__n_estimators:
      - 100
      - 200
      - 300
    regressor__learning_rate:
      - 0.01
      - 0.1
    regressor__max_depth:
      - 3
      - 4
      - 5
      - 6
  signature_depth: 6
  scorer: neg_mean_absolute_error

classification:
  param_grid:
    n_estimators:
      - 100
      - 200
      - 300
    learning_rate:
      - 0.01
      - 0.1
    max_depth:
      - 3
      - 4
      - 5
      - 6
  signature_depth: 6
  scorer: f1
   




  
    

