test_ratio: 0.3

eol:
  param_grid:
    regressor__n_estimators:
      - 100
      - 200
      - 300
    regressor__learning_rate:
      - 0.01
      - 0.1
    regressor__max_depth:
      - 3
      - 4
      - 5
      - 6
  signature_depth: 3

rul:
  param_grid:
    regressor__n_estimators:
      - 100
      - 200
      - 300
    regressor__learning_rate:
      - 0.01
      - 0.1
    regressor__max_depth:
      - 3
      - 4
      - 5
      - 6
  signature_depth: 6

classification:
  param_grid:
    n_estimators:
      - 100
      - 200
      - 300
    learning_rate:
      - 0.01
      - 0.1
    max_depth:
      - 3
      - 4
      - 5
      - 6
  signature_depth: 6
   




  
    

